export const ActionTypes = {
  USER: "USER",
  REMOVE_USER: "REMOVE_USER",
  ADD_CART: "ADD_CART",
  REMOVE_CART: "REMOVE_CART",
  ADD_WISHLIST: "ADD_WISHLIST",
  REMOVE_WISHLIST: "REMOVE_WISHLIST",
  LOADING: "LOADING",
  THEME: "THEME",
  ALERT: "ALERT",
};
