# Generated by Django 5.1.1 on 2024-09-22 08:10

from django.db import migrations, models

import common.model_helpers


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0002_remove_order_designs_remove_order_price_paid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="image_response",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="display_picture_response",
            field=models.JSONField(
                blank=True,
                default=common.model_helpers.default_image_response,
                null=True,
            ),
        ),
    ]
