# Generated by Django 5.1.1 on 2024-09-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_design_image_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
