# Generated by Django 5.1.1 on 2025-01-19 09:13

import django.core.validators
from django.db import migrations

import common.custom_fields


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_cart_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="card_number",
        ),
        migrations.AddField(
            model_name="card",
            name="encrypted_char_field",
            field=common.custom_fields.EncryptField(
                blank=True,
                max_length=128,
                validators=[django.core.validators.MinLengthValidator(16)],
            ),
        ),
    ]
