# Generated by Django 5.1.1 on 2025-01-19 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_remove_card_card_number_card_encrypted_char_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="encrypted_char_field",
            new_name="card_number",
        ),
    ]
