export const ActionTypes = {
 USER_LOGGED: "USER_LOGGED",
 REMOVE_USER: "REMOVE_USER",
 ADD_PROFILE_DESIGN: "ADD_PROFILE_DESIGN",
 EDIT_PROFILE_DESIGN: "EDIT_PROFILE_DESIGN",
 DELETE_PROFILE_DESIGN: "DELETE_PROFILE_DESIGN",
 ADD_CART: "ADD_CART",
 REMOVE_CART: "REMOVE_CART",
 ADD_WISHLIST: "ADD_WISHLIST",
 REMOVE_WISHLIST: "REMOVE_WISHLIST",
 ALL_DESIGNS: "ALL_DESIGNS",
};